name: GCP Cloud Functions Deployment
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev # Fetches the env variables for dev
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          token_format : "access_token"
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Deploy Cloud Function
        run: |
          pwd
          ls -lrt *
          ls -lrt */*
          gcloud functions deploy gcp-test\
            --gen2 \
            --runtime python311 \
            --trigger-http \
            --allow-unauthenticated \
            --source 'cloud_functions/big_query_dll' \
            --entry-point trigger_bq
